// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebPostgreSQL.Models;

#nullable disable

namespace Projeto_Fatec.Migrations.ContextoConsultaMigrations
{
    [DbContext(typeof(ContextoConsulta))]
    partial class ContextoConsultaModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebPostgreSQL.Models.Consulta", b =>
                {
                    b.Property<int>("ConsultaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ConsultaId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConsultaId"));

                    b.Property<string>("Comodidade_Consulta")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("Comodidade_Consulta");

                    b.Property<DateTime?>("DTConsulta_Consulta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DTConsulta_Consulta");

                    b.Property<string>("Descricao_Consulta")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("Descricao_Consulta");

                    b.Property<string>("ExameClinico_Consulta")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ExameClinico_Consulta");

                    b.Property<int>("MedicoId")
                        .HasColumnType("integer")
                        .HasColumnName("MedicoId");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("PacienteId");

                    b.Property<string>("Poblemas_Consulta")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Poblemas_Consulta");

                    b.Property<string>("RaioX_Consulta")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("RaioX_Consulta");

                    b.Property<string>("Tratamento_Consulta")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Tratamento_Consulta");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioId");

                    b.HasKey("ConsultaId");

                    b.ToTable("Consulta");
                });
#pragma warning restore 612, 618
        }
    }
}
